<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTkKRexR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTkKRexR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTkKRexR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTkKRexR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTkKRexR\App_KernelDevDebugContainer([
    'container.build_hash' => 'TkKRexR',
    'container.build_id' => 'b664925e',
    'container.build_time' => 1666819641,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTkKRexR');
