<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUqLQxsz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUqLQxsz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUqLQxsz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUqLQxsz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUqLQxsz\App_KernelDevDebugContainer([
    'container.build_hash' => 'UqLQxsz',
    'container.build_id' => '09b935ba',
    'container.build_time' => 1666358624,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUqLQxsz');
