<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container47H5cCd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container47H5cCd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container47H5cCd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container47H5cCd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container47H5cCd\App_KernelDevDebugContainer([
    'container.build_hash' => '47H5cCd',
    'container.build_id' => 'd9467abf',
    'container.build_time' => 1666164717,
], __DIR__.\DIRECTORY_SEPARATOR.'Container47H5cCd');
